
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
replication_factor = 1
consistency_mode = "consistent"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

[s3_api]
api_bind_addr = "0.0.0.0:9000"
s3_region = "garage"

[admin]
api_bind_addr = "0.0.0.0:3903"
admin_token = "test-admin-token-for-ci"
metrics_token = "test-metrics-token-for-ci"
