import { DEFAULT_AEAD_KEY_LENGTH_BYTES } from '../shared/Consts';

/**
 * AEAD (Authenticated Encryption with Associated Data)
 * Used for encrypting the actual content (RootFile) with symmetric keys
 *
 * In production: Use AES-256-GCM
 */
export type RawAEADKey = Uint8Array<ArrayBuffer> & { readonly __tag?: 'RawAEADKey' };
export type AEADCryptoKey = CryptoKey & { readonly __tag?: 'AEADCryptoKey' };

export class AEADError extends Error {
  constructor(message: string, public readonly code: string) {
    super(message);
    this.name = 'AEADError';
  }
}

export class AEAD {
  private static readonly KEY_LENGTH = DEFAULT_AEAD_KEY_LENGTH_BYTES; // 256 bits / 32 bytes
  private static readonly IV_LENGTH = 12; // 96 bits recommended for GCM
  private static readonly ALGORITHM = 'AES-GCM';
  private static readonly EXPORTABLE_KEY = false;

  /**
   * Generates a cryptographically secure random 256-bit key
   * @returns {RawAEADKey} 32-byte Uint8Array suitable for AES-256-GCM
   */
  static generateRawAEADKeyData(): RawAEADKey {
    return crypto.getRandomValues(new Uint8Array(this.KEY_LENGTH)) as RawAEADKey;
  }

  /**
   * Imports a raw key into a CryptoKey object for encryption/decryption
   * @param {RawAEADKey} rawKey - 32-byte raw key data generated by generateRawAEADKeyData()
   * @returns {Promise<AEADCryptoKey>} CryptoKey configured for AES-GCM operations
   * @throws {AEADError} If key length is invalid
   */
  static async importAEADKey(rawKey: RawAEADKey): Promise<AEADCryptoKey> {
    if (rawKey.length !== this.KEY_LENGTH) {
      throw new AEADError(
        `Invalid key length: expected ${this.KEY_LENGTH} bytes, got ${rawKey.length}`,
        'INVALID_KEY_LENGTH',
      );
    }
    try {
      return (await crypto.subtle.importKey('raw', rawKey, { name: this.ALGORITHM }, this.EXPORTABLE_KEY, [
        'encrypt',
        'decrypt',
      ])) as AEADCryptoKey;
    } catch (error) {
      throw new AEADError(
        `Failed to import key: ${error instanceof Error ? error.message : 'unknown error'}`,
        'KEY_IMPORT_FAILED',
      );
    }
  }

  /**
   * Encrypts plaintext using AES-256-GCM
   * Format: [12-byte IV][ciphertext + auth tag (16 bytes)]
   * @param {AEADCryptoKey} key - CryptoKey for encryption
   * @param {Uint8Array<ArrayBuffer>} plaintext - Data to encrypt
   * @returns {Promise<Uint8Array>} Encrypted data with prepended IV
   * @throws {AEADError} If encryption fails
   */
  static async encrypt(key: AEADCryptoKey, plaintext: Uint8Array<ArrayBuffer>): Promise<Uint8Array> {
    const iv = crypto.getRandomValues(new Uint8Array(this.IV_LENGTH));
    try {
      const encrypted = await crypto.subtle.encrypt({ name: this.ALGORITHM, iv }, key, plaintext);
      const result = new Uint8Array(iv.length + encrypted.byteLength);
      result.set(iv, 0);
      result.set(new Uint8Array(encrypted), iv.length);
      return result;
    } catch (error) {
      throw new AEADError(
        `Encryption failed: ${error instanceof Error ? error.message : 'unknown error'}`,
        'ENCRYPTION_FAILED',
      );
    }
  }

  /**
   * Decrypts ciphertext encrypted with AES-256-GCM
   * @param {AEADCryptoKey} key - CryptoKey for decryption
   * @param {Uint8Array} ciphertext - Encrypted data with prepended IV
   * @returns {Promise<Uint8Array>} Decrypted plaintext
   * @throws {AEADError} If decryption or authentication fails
   */
  static async decrypt(key: AEADCryptoKey, ciphertext: Uint8Array): Promise<Uint8Array> {
    if (ciphertext.length < this.IV_LENGTH) {
      throw new AEADError(
        `Ciphertext too short: expected at least ${this.IV_LENGTH} bytes, got ${ciphertext.length}`,
        'INVALID_CIPHERTEXT_LENGTH',
      );
    }
    try {
      const iv = ciphertext.slice(0, this.IV_LENGTH);
      const encrypted = ciphertext.slice(this.IV_LENGTH);

      const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, key, encrypted);
      return new Uint8Array(decrypted);
    } catch (error) {
      throw new AEADError('Decryption failed: authentication tag mismatch or corrupted data', 'DECRYPTION_FAILED');
    }
  }
}
