name              = "lattice-service"
main              = "index.cf.js"
compatibility_date = "2025-05-07"
compatibility_flags = [ "nodejs_compat_v2" ]
cwd = "../.."
send_metrics = false


[dev]
port = 8787


